default_settings: null
behaviors:
  PedestrianAgent:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-3
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 500
    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 3
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    checkpoint_interval: 10000
    threaded: true

env_settings:
  env_path: PedestrianAgent
  env_args: null
  base_port: 5004
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: PedestrianNew
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
debug: false
